version: '3'
services:

    segurosaas-bd:
        build: ./seguros-saas-bd
        image: vrigosilva/segurosaas-bd
        container_name: segurosaas-bd
        networks: 
            - segurosaas-net
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "seguros_saas"
        ports:
            - 3306:3306
        
    segurosaas-web:
        build: ./seguros-saas-web
        image: vrigosilva/segurosaas-web
        container_name: segurosaas-web
        ports:
            - 8081:8081
        networks: 
            - segurosaas-net
        depends_on:
            - segurosaas-bd
        command: ["./wait-for", "segurosaas-bd:3306", "-t", "30", "--", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]     
        
    segurosaas-produto:
        build: ./seguros-saas-ws/seguros-saas-produto
        image: vrigosilva/segurosaas-produto
        container_name: segurosaas-produto
        ports:
            - 8082:8082
        networks: 
            - segurosaas-net
        depends_on:
            - segurosaas-bd
        command: ["./wait-for", "segurosaas-bd:3306", "-t", "30", "--", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]  

    segurosaas-venda:
        build: ./seguros-saas-ws/seguros-saas-venda
        image: vrigosilva/segurosaas-venda
        container_name: segurosaas-venda
        ports:
            - 8083:8083
        networks: 
            - segurosaas-net
        depends_on:
            - segurosaas-bd
        command: ["./wait-for", "segurosaas-bd:3306", "-t", "30", "--", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]  
            
networks:
    segurosaas-net:
        driver: bridge
